# Generated by Django 5.0.2 on 2024-02-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='name',
            new_name='party_name',
        ),
    ]
